language: node_js

node_js: 14

branches:
  only:
  - master

cache:
  directories:
  - node_modules

script:
- npm test
- npm run build

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: npm
  email: vdsabev@gmail.com
  api_key:
    secure: fi79h93i6SgLOTcsKbneBPPAnyv82uq1oKC+soZn4vbO3bSuybJZRe5WGDc5xpcUFUU8oNmxs60r9h7Ac35GMYrPQ+kpjDb684rgg56fvvI32axUdLvAWk65nAypJh/rMq0UQlt5qcwWgdduiWawWl4EQvi0QvDZHWNdLRmvbdrbZiEgL3DVoaqSHxaiEJ/pkqSBWXH6QNcsPOxlGQN+KQ+0iaBGrH4ToD1nUyLetK5256CjP6NvWde2Jt0V9ub3T1ollFUWtZEPfw86vT9ozfRs/9A8/aB4dKsxex9ywS0J/P37ZZpki6nYzOt6FZ9nP9ccirL6XE5FN6xbaqzJJ1NnEadp03tXpgg7TtP5/Nf4eE0Ske/ILGmPJwvOvJGzuq+jeocTrHIzujKrCoVfb05HdUQtASlJzsH9iwlGHGFqXaCGDZEo2RMd/BQhls3KofE5MKYgqIO7dOzGQII9epcrn68Olqhy/dxaioN84TRCuxv9CJUM+8sL2XLcPJm9ryrZI/G0hi9WQaDFc7b4Ls2AcGmXUmbFY+Z5JIUJEPhHm07JYOx7ta+jNTW54VmJQILStxZrs8bVUjq4jHtHgrSjf7d0G+di1bs59aJ1gTZWjDjJ5Ookk6tQTDSQkGZ0IUsiLq2ReKaEvSCGvMeCtfdPE1o6ekwZmQZRm8btvH0=
  on:
    repo: vdsabev/pathern
  skip_cleanup: true
